/**
 * Catalog invariants — the durable guard that keeps `data/models.json` a clean catalog
 * of real labs' canonical, normalized model ids (and overrides that always resolve).
 *
 * These are STRUCTURAL invariants enforced on every CI run. Both files are generated by
 * `scripts/generate-catalog.ts` (from the `src/labs/` + `src/provider/` registries); this test
 * catches the regressions a structural check can (underscores, casing, custom SKUs, broken refs).
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { ModelListSchema } from '../schemas/model'
import { ProviderModelListSchema } from '../schemas/provider-models'

const dataDir = join(fileURLToPath(import.meta.url), '..', '..', '..', 'data')
const modelsRaw = JSON.parse(readFileSync(join(dataDir, 'models.json'), 'utf8'))
const providerModelsRaw = JSON.parse(readFileSync(join(dataDir, 'provider-models.json'), 'utf8'))
const models = modelsRaw.models as Array<{
  id: string
  contextWindow?: number
  maxOutputTokens?: number
}>
const overrides = providerModelsRaw.overrides as Array<{
  providerId: string
  modelId: string
  name?: string
}>

// normalized lab id: lowercase, alphanumerics joined by single hyphens (size/version kept)
const NORMALIZED = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
// shapes a lab never publishes: custom SKUs, double-dash vendor wrappers, routers
const JUNK = /(?:-vip|-ssvip|-cursor|-all|-nx|-gizmo|-mobile)$|--|^duo-chat-|\bauto\b/

describe('catalog invariants (data/*.json)', () => {
  const ids = models.map((m) => m.id)
  const baseIds = new Set(ids)

  it('base model ids are unique', () => {
    expect(ids.filter((id, i) => ids.indexOf(id) !== i)).toEqual([])
  })

  it('every base id is a normalized lab id (lowercase, single-hyphen separated)', () => {
    expect(ids.filter((id) => !NORMALIZED.test(id))).toEqual([])
  })

  it('no junk id patterns (custom SKUs / vendor wrappers / routers)', () => {
    expect(ids.filter((id) => JUNK.test(id))).toEqual([])
  })

  it('every override resolves to a base row or carries a standalone name', () => {
    const broken = overrides
      .filter((o) => !baseIds.has(o.modelId) && !o.name)
      .map((o) => `${o.providerId}/${o.modelId}`)
    expect(broken).toEqual([])
  })

  it('maxOutputTokens never exceeds contextWindow', () => {
    const bad = models.filter((m) => m.contextWindow && m.maxOutputTokens && m.maxOutputTokens > m.contextWindow)
    expect(bad.map((m) => m.id)).toEqual([])
  })

  it('models.json conforms to ModelListSchema', () => {
    const r = ModelListSchema.safeParse(modelsRaw)
    expect(r.success ? [] : r.error.issues.slice(0, 5)).toEqual([])
  })

  it('provider-models.json conforms to ProviderModelListSchema', () => {
    const r = ProviderModelListSchema.safeParse(providerModelsRaw)
    expect(r.success ? [] : r.error.issues.slice(0, 5)).toEqual([])
  })

  it('the validators actually reject known-bad shapes', () => {
    expect(NORMALIZED.test('GLM-4_5')).toBe(false) // uppercase + underscore
    expect(NORMALIZED.test('anthropic--claude-3-5-sonnet')).toBe(false) // double-dash
    expect(NORMALIZED.test('claude-3-5-sonnet@20240620')).toBe(false) // @date
    expect(JUNK.test('gpt-4o-image-vip')).toBe(true)
    expect(JUNK.test('duo-chat-gpt-5-2')).toBe(true)
    expect(JUNK.test('claude-3-5-sonnet')).toBe(false) // real id must pass
  })
})
